package com.imooc.order.dto;

import com.imooc.order.pojo.OrderDetail;
import com.imooc.order.pojo.OrderTemp;

import java.math.BigDecimal;
import java.util.List;

public class OrderDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.orderid
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    private String orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyername
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    private String buyername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyerphone
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    private String buyerphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyeraddress
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    private String buyeraddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyeropenid
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    private String buyeropenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.orderamount
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    private BigDecimal orderamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.orderstatus
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    private Integer orderstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.paystatus
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    private Integer paystatus;
    private List<OrderTemp> orderDetailList;

    public String getOrderid() {
        return orderid;
    }

    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }

    public String getBuyername() {
        return buyername;
    }

    public void setBuyername(String buyername) {
        this.buyername = buyername;
    }

    public String getBuyerphone() {
        return buyerphone;
    }

    public void setBuyerphone(String buyerphone) {
        this.buyerphone = buyerphone;
    }

    public String getBuyeraddress() {
        return buyeraddress;
    }

    public void setBuyeraddress(String buyeraddress) {
        this.buyeraddress = buyeraddress;
    }

    public String getBuyeropenid() {
        return buyeropenid;
    }

    public void setBuyeropenid(String buyeropenid) {
        this.buyeropenid = buyeropenid;
    }

    public BigDecimal getOrderamount() {
        return orderamount;
    }

    public void setOrderamount(BigDecimal orderamount) {
        this.orderamount = orderamount;
    }

    public Integer getOrderstatus() {
        return orderstatus;
    }

    public void setOrderstatus(Integer orderstatus) {
        this.orderstatus = orderstatus;
    }

    public Integer getPaystatus() {
        return paystatus;
    }

    public void setPaystatus(Integer paystatus) {
        this.paystatus = paystatus;
    }

    public List<OrderTemp> getOrderDetailList() {
        return orderDetailList;
    }

    public void setOrderDetailList(List<OrderTemp> orderDetailList) {
        this.orderDetailList = orderDetailList;
    }
}
