package com.imooc.order.pojo;

import javax.persistence.Id;
import javax.persistence.Table;
import java.math.BigDecimal;
import java.util.Date;

@Table(name = "order_master")
public class OrderMaster {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.orderid
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    @Id
    private String orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyername
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    private String buyername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyerphone
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    private String buyerphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyeraddress
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    private String buyeraddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.buyeropenid
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    private String buyeropenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.orderamount
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    private BigDecimal orderamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.orderstatus
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    private Integer orderstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.paystatus
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    private Integer paystatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.createtime
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_master.updatetime
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.orderid
     *
     * @return the value of order_master.orderid
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.orderid
     *
     * @param orderid the value for order_master.orderid
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.buyername
     *
     * @return the value of order_master.buyername
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    public String getBuyername() {
        return buyername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.buyername
     *
     * @param buyername the value for order_master.buyername
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    public void setBuyername(String buyername) {
        this.buyername = buyername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.buyerphone
     *
     * @return the value of order_master.buyerphone
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    public String getBuyerphone() {
        return buyerphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.buyerphone
     *
     * @param buyerphone the value for order_master.buyerphone
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    public void setBuyerphone(String buyerphone) {
        this.buyerphone = buyerphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.buyeraddress
     *
     * @return the value of order_master.buyeraddress
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    public String getBuyeraddress() {
        return buyeraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.buyeraddress
     *
     * @param buyeraddress the value for order_master.buyeraddress
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    public void setBuyeraddress(String buyeraddress) {
        this.buyeraddress = buyeraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.buyeropenid
     *
     * @return the value of order_master.buyeropenid
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    public String getBuyeropenid() {
        return buyeropenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.buyeropenid
     *
     * @param buyeropenid the value for order_master.buyeropenid
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    public void setBuyeropenid(String buyeropenid) {
        this.buyeropenid = buyeropenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.orderamount
     *
     * @return the value of order_master.orderamount
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    public BigDecimal getOrderamount() {
        return orderamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.orderamount
     *
     * @param orderamount the value for order_master.orderamount
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    public void setOrderamount(BigDecimal orderamount) {
        this.orderamount = orderamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.orderstatus
     *
     * @return the value of order_master.orderstatus
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */


    public Integer getOrderstatus() {
        return orderstatus;
    }

    public void setOrderstatus(Integer orderstatus) {
        this.orderstatus = orderstatus;
    }

    public void setPaystatus(Integer paystatus) {
        this.paystatus = paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.paystatus
     *
     * @return the value of order_master.paystatus
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    public Integer getPaystatus() {
        return paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.createtime
     *
     * @return the value of order_master.createtime
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.createtime
     *
     * @param createtime the value for order_master.createtime
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.updatetime
     *
     * @return the value of order_master.updatetime
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.updatetime
     *
     * @param updatetime the value for order_master.updatetime
     *
     * @mbggenerated Mon Jul 30 23:59:40 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}