eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/db1?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
mybatis:
  type-aliases-package: com.imooc.order.pojo
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: com.imooc.order.utils.MyMapper
  not-empty: false
  identity: MYSql
server:
  port: 8083
#自定义配置Ribbon方式
#PRODUCT:
 #ribbon:
   #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

